### ISSUE TITLE
Jamf Pro Server Usage?

### ISSUE THREAD

**Issue by albiii** [erikberglund/ProfileCreator#113]
Do you use your profiles with an MDM? If so do you have to sign them? I love your tool but I am unable to get the profiles to work. My guess is because they are not signed.

**Comment by apizz** [comment]
@albiii in my experience, Jamf doesn't process uploading profiles unless they deal with preference domains they recognize.  It's not smart enough to automatically stick these in the "Custom Settings" payload.

As a result, I would recommend building your desired payload in ProfileCreator, switch over to the XML view (rather than GUI), and copy and paste everything into a PLIST that's named the same as the preference domain to be managed.  Remove all of the profile-specific bits: `PayloadDisplayName`, `PayloadIdentifier`, etc.  Upload that PLIST into a new profile as part of the Custom Settings payload.  Test and make sure the desired settings are managed.

**Comment by reidrichardson** [comment]
Do you have a mac development certificate for either dev or prod?  I sign with one from my organization and upload it to jamf pro.  You cannot edit it once in jamf but it will deploy it from what i can tell.  Not sure if this just converts it to a preferences payload or not but it works

**Comment by erikberglund** [comment]
@albiii This issue is unfortunately nothing we can fix as it's a Jamf issue.

If you are uploading an unsigned profile that is using Apples defined payloads, i.e. any payload that Jamf has in the GUI, Jamf will read the settings and set those in their GUI. But that also means that they will add all of their other settings along with what you wanted to modify.

This behaviour is basically the reason why I created this tool, as it doesn't give admins any choice on what to manage, but Jamf decides a buch of stuff by themselves.

So, that is why you HAVE to sign profiles that are using Apple-payloads.

Those profiles cannot be added as "custom" either as then macOS will not read them correctly.

If you have third party profiles, like for Firefox or Nomad, then you can select to change the profile style to XML when you export.

Then you don't have to sign, but again, that only works for third party payloas.

I will close this as there is nothing more we can do. Please file an issue with jamf so they change their behaviour.

**Comment by kwmatan** [comment]
This environment lot of non-MDM installed profiles.

Further, it seems some of the same configs were attempted with different names.

The pattern I can find is they were all built with ProfileCreator.

I have so many different identifiers - I'm wondering - could I scan using profiles -P and somehow parse the output in such that if it includes: com.github.erikberglund.ProfileCreator.*

It would then use the:

profiles remove -identifier "$variable"
Asking if this is the only approach
