### ISSUE TITLE
Unable to create an exchange profile that prompts for email and password

### ISSUE THREAD

**Issue by ofirgalcon** [erikberglund/ProfileCreator#132]
This is possible in Apple's iPhone Config Util.

**Comment by erikberglund** [comment]
The manifest has been updated to allow this now. You need to select "Manual" as the distribution because the keys are still required when the profile is "pushed" by an MDM. I also added the `IdentificationUUID` key to the exchange payload and I have tried it and it works as expected on the current version of ProfileCreator aswell.
