### ISSUE TITLE
Add white payload category buttons for dark mode

### ISSUE THREAD

**Issue by apizz** [erikberglund/ProfileCreator#149]
In dark mode, the payload category buttons are not as clear as they could be.  Can we get some white outline buttons for dark mode to make it clearer?

![DarkMode](https://user-images.githubusercontent.com/11789931/55972518-a614d400-5c51-11e9-9220-1961e1cd2b7a.png)

**Comment by erikberglund** [comment]
I think I found the issue with this bug, It's because I got a new computer and compiled the application on macOS 10.13 instead of 10.14. I believe it needs to be compiled on 10.14 to get the correct configuration to recognise the DarkMode enabled icons and notifications.

Because the xml-view is also not working as expected.

So, its a build bug and nothing in code which was great for me.

**Comment by apizz** [comment]
Confirmed in latest v0.3.0 release that buttons are showing as white in dark mode.
![Screen Shot 2019-05-17 at 11 13 25 AM](https://user-images.githubusercontent.com/11789931/57937986-2522ab00-7895-11e9-9ca4-b6090ebc9297.png)
![Screen Shot 2019-05-17 at 11 13 29 AM](https://user-images.githubusercontent.com/11789931/57937992-28b63200-7895-11e9-9f81-61b903ba5ef8.png)
