### ISSUE TITLE
External dependencies should use subtree instead of submodule

### ISSUE THREAD

**Issue by ygini** [erikberglund/ProfileCreator#40]
Hello

Regarding third part project used in your code, you should use git subtree instead of submodule to simplify the source management

http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/

subtree is appropriate to import a required third part repo into a specific project.
submodule is made to make inclusion of specific part of code optional. Imagine you're working on a big project with client, server and lib, you might not want to clone everything when you code but still have a centralized repo with everything read for build.

**Comment by erikberglund** [comment]
I have not used subtrees before, but I can see the benefits of not having all code in the repo in case of unforseen changes and not needing to also initialize the submodules.

I replaced the only current submodule with a subtree.

**Comment by erikberglund** [comment]
The subtree worked, but the repo had been updated and the new version doesn't compile on Xcode 7. So, I'm trying to find a way to add a subtree for a tag. Will post when I figured out how to do that and updated the repo with a working subtree.

**Comment by ygini** [comment]
```git subtree pull  -P <prefix> <repository> <ref>```
 ref is the tag

**Comment by erikberglund** [comment]
I got that far, but it ends with tons of conflicts that I can't find a way to solve automatically.

**Comment by erikberglund** [comment]
I backed up, removed all recent commits and instead used `git subtree add   --prefix=<prefix> <commit>` to select the last commit for the tag I wanted, and then I got the correct version that builds as it should.

**Comment by erikberglund** [comment]
After testing this some, I don't know if it's a good idea. I've had lots of trouble with using a subtree where the submodule just work. That plus all the code gets included in the repository which makes it harder to see what belongs to the project. Now for example, If a modification has been made to a file in a submodule by xcode or by mistaker etc, i normally just move to the submodule folder and do a `git checkout .` and all changes are reverted. But, I don't know how to do that with the subtree.

I'm leaning toward moving back to submodules so I can focus on the project instead of git.

**Comment by erikberglund** [comment]
With some more testing, I'll levant as is now with subtrees, as it would make it a lot easier for contributors to always have the correct repo including included items. And, with any issues, I'll try to figure them out.
