### ISSUE TITLE
Smartcard Profile - Enable Certificate Trust Validation

### ISSUE THREAD

**Issue by golbiga** [erikberglund/ProfileCreator#46]
In the app there is only enable/disable for checkCertificateTrust. The value for this key should be an integer: 

0 certificate trust check is turned off
1 certificate trust check is turned on
2 certificate trust check is turned on and revocation check is set to the soft level
3  certificate trust check is turned on and revocation check is set to the hard level

**Comment by erikberglund** [comment]
Thank you, that is correct and I have updated that in the application for next release. I must have missed or mixed it up when going through the keys as I go through each key one by one in every payload, but mistakes are bound to happen. 

Profile Manager seems to only show the boolean as well, I might have been fooled by that. 

Here is the updated change: [Smart Card Manifest](https://github.com/erikberglund/ProfileManifests/blob/master/AppleManifests/com.apple.smartcard.plist#L178-L193). I'm not sure how to word the different settings, it will be shown as a pop-up button. Currently, I just set them to:

**Certificate Trust Validation**
* Off
* On
* On and revocation check is set to the soft level
* On and revocation check is set to the hard level

Do you have any other suggestions?

They show up like this:

![screen shot 2018-07-02 at 20 13 52](https://user-images.githubusercontent.com/1296345/42179487-7e4fd77c-7e34-11e8-9c23-bfb90bf6ac47.png)

**Comment by golbiga** [comment]
Looks good to me. Thanks for the quick fix! The only thing I would maybe change is:

Disable SmartCard should be Allow Smart Card since the default is true
Disable User Pairing should be User Pairing since the default is true 

Also I noticed `<!-- FIXME: Shouldn't this key disable the allowSmartCard setting?, what if that is set to false?-->` enforceSmartCard requires that allowSmartCard be enabled. If enforceSmartCard is set to false users can login w/ their smartcard but they can also still use a password. Hope this helps.

Thanks
Allen

**Comment by erikberglund** [comment]
The "Disable" instead of "Allow" comes from Profile Manager and from one of the documentation documents. I think it is that way to make it more explicit that you want to disable it, as Allow is the default and therefore should probably not even be set at all if you want to allow it? (as it already is).

To set the title to "Disable", it's more clear that the settings are there so you to disable it.

If it said Allow, it could be confusing if you don't know what the default is. An admin might think they have to add a setting that is already a default os setting if you know what I mean.

I don't know anything about smart cards, so in this case, it might be required to explicitly allow smart cards and user pairing? That you probably know. But the naming is probably to make it more obvious that this setting only really is necessary if you want to disable it. Else, just don't set that key.

So, is it so that you have to set the `allowSmartCard` key to true to enable smart cards? If so, I will change to make it more clear.

Regarding the `enforceSmartCard` key, is it required that the key `allowSmartCard` is set in the profile, or can you only add `enforceSmartCard` and since the os default is to allow smart cards, then they are enforced?

Now I'm assuming that smart cards are os default allowed. You can probably help me. Hope I made sense with this post :)

**Comment by erikberglund** [comment]
I'm going to close this as the original issue is fixed. Please open a new issue if anything is wrong or missing.
