### ISSUE TITLE
Login Window Settings

### ISSUE THREAD

**Issue by roodavis** [erikberglund/ProfileCreator#75]
I think the selection for the Login Prompt needs attention. When "Name and password text fields" is selected the Show Full Name value shows as false in the XML and the HideAdminUser and ShowOtherUsers_Managed keys are not present. Which then shows the list of users along with Admin Users and no "Other" field.

**Comment by erikberglund** [comment]
I have tested this payload and I could not find anything incorrect with it's current settings.

`SHOWFULLNAME` = `false` means that only the username and password textfields are show.

And if only the text fields the "other" and admin users etc. cannot be shown so they are unneccesary.

One thing to note when testing this is this setting requires a restart to take effect.

**Comment by erikberglund** [comment]
Also, if you have FileVault enabled, you will see the EFI-login which is not the same as the LoginWindow. 

If you have that enabled you need to logout after you get logged in to see the loginwindow settings.

**Comment by 16BitJunkie** [comment]
I also noticed this today. Chose to just show Name and Password, still shows local admin account and "other user". This persists after a reboot.

**Comment by erikberglund** [comment]
So you dont see the text fields? Post the profile you are using as i Cant replicate this. It works as expected on 10.13 and 10.14 when i tested it.

**Comment by 16BitJunkie** [comment]
[Default Login Window.mobileconfig.zip](https://github.com/erikberglund/ProfileCreator/files/2456467/Default.Login.Window.mobileconfig.zip)

**Comment by erikberglund** [comment]
@16BitJunkie @roodavis Thanks for both of your reports. There were multiple errors here that I have fixed, will upload shortly. But why I was confused was because of the inverted boolean, but now that is fixed.

And, the reason nothing worked was also because of the wrong scope. That I will also adress.

**Comment by erikberglund** [comment]
So, what was the error was this:

1. This payload allowed to export in the User scope, which is not valid. I exported for system which is why it worked when I tested.

2. The `SHOWFULLNAME` has an inverted boolean, and this issue was brought up some time ago and I fixed it, and the index for this specific manifest had not been updated so that fix never got used by other clients. So that is also fixed.

I'm going through every manifest a few a day so this would have been caught by that, and I have found similar smaller issues with other manifests so I think after that is done all manifests would have been checked one extra time to avoid more issues. But, there will always be issues so please keep opening these issues.

It's these reports that will make this app great. Thank you!

**Comment by erikberglund** [comment]
Now the manifest is uploaded, so you can update the manifests in the app from Preferences -> Payloads and the new settings will be applied.

**Comment by 16BitJunkie** [comment]
Wanted to hop on here again. Not trying to be a bother, but even after updating the manifests the boolean is showing up inverted. I can switch it to true manually so nbd, just thought I'd let you know!

**Comment by erikberglund** [comment]
@16BitJunkie Thanks again, reporting issues is the best thing to do and I want as many as possible so the app can get better.

This was again an edge issue, I have fixed this in the manifest, and it is uploaded correctly, but the script that creates the index file used to see if there are updates did not catch that there was a change when I only changed the order of two keys in an array, so the index stayed as 1 and the app did not download the new setting.

I have fixed that now, so please try again.

**Comment by 16BitJunkie** [comment]
Works perfectly now!
