### ISSUE TITLE
TCC in next release?

### ISSUE THREAD

**Issue by pedroaddigy** [erikberglund/ProfileCreator#78]
Will you add TCC options  in the next release?

**Comment by erikberglund** [comment]
TCC was added two versions ago I think. But i understand if you had trouble finding it as the filter only searches for the display name and not the payload type. That will be fixed for the next version.

Today you can find the tcc profile with its name Privacy Policy: Control

**Comment by pedroaddigy** [comment]
I wonder if we can integrate your profileConfigurator into Addigy... versus
us creating our own?



Click Here to schedule in my calendar:  *https://calendly.com/addigy
<https://calendly.com/addigy>*

[image: Addigy, Inc] <http://www.addigy.com/>
*Peter Stebbins *
*Eastern USA - Europe Sales Director*
Main: 305-330-6677 x104
*Mac Cloud IT Management Platform*

**Comment by grahamgilbert** [comment]
https://tenor.com/HSn6.gif

**Comment by erikberglund** [comment]
@pedroaddigy I have added the search functionality to the next update so one can search for the PayloadType as well, that will find the payload when searching for "TCC" for example.

No, I have not used Addigy, but I think it would absolutely be possible to integrate with any MDM or management tool.

**Comment by pedroaddigy** [comment]
When is this new release?

Let's schedule a call.



Click Here to schedule in my calendar:  *https://calendly.com/addigy
<https://calendly.com/addigy>*

[image: Addigy, Inc] <http://www.addigy.com/>
*Peter Stebbins *
*Northeast USA - Europe Sales Director*
Main: 305-330-6677 x104
*Apple Cloud IT Management Platform*

**Comment by pedroaddigy** [comment]
Can you send me a screenshot of this TCC area?!  This could help me close
as deal today!



Click Here to schedule in my calendar:  *https://calendly.com/addigy
<https://calendly.com/addigy>*

[image: Addigy, Inc] <http://www.addigy.com/>
*Peter Stebbins *
*Northeast USA - Europe Sales Director*
Main: 305-330-6677 x104
*Apple Cloud IT Management Platform*

**Comment by erikberglund** [comment]
If you're on macadamias slack, there is a #profilecreator channel. In there I have a short video where I'm adding AppleScript TCC rules through drag and drop here: https://macadmins.slack.com/archives/C2N7MED7G/p1537989407000100

Also here for adding all other TCC rules via drag and drop:
https://macadmins.slack.com/archives/C2N7MED7G/p1534276316000100

Since this tool is basically a manifest-interpreter. The GUI is completely generated from a configuration file it looks very similar across all payloads. The only "hardcoded" UI is in certain value import conversions where one thing is dropped and a sheet is shown on how to handle that item. But most is just created on the fly depending on the manifest file.

So that's why the TCC UI is a bunch of tableviews. It's always a possibility to create custom UIs but I have not needed that yet, since drag and rop to fill all fields have served very good most of the time. But I have some very nice features planned to improve the UI even more, but time is currently my biggest issue. :)

**Comment by pedroaddigy** [comment]
What is your email?


Click Here to schedule in my calendar:  *https://calendly.com/addigy
<https://calendly.com/addigy>*

[image: Addigy, Inc] <http://www.addigy.com/>
*Peter Stebbins *
*Northeast USA - Europe Sales Director*
Main: 305-330-6677 x104
*Apple Cloud IT Management Platform*



>

**Comment by erikberglund** [comment]
You can use erik.berglund@mac.com
